package main

import (
	"github.com/Devorein/go-by-examples/examples"
)

func main() {
	// examples.HelloWorld()
	// examples.Values()
	// examples.Variables()
	// examples.Constants()
	// examples.For()
	// examples.IfElse()
	// examples.Switch()
	// examples.Arrays()
	// examples.Slices()
	// examples.Maps()
	// examples.Range()
	// examples.Functions()
	// examples.Closures()
	// examples.Recursions()
	// examples.Pointers()
	// examples.Struct()
	// examples.Methods()
	// examples.Interfaces()
	// examples.Errors()
	// examples.Goroutines()
	// examples.Channels()
	// examples.BufferedChannels()
	// examples.ChannelSync()
	// examples.ChannelDirections()
	// examples.MultiChannelSync()
	// examples.Timeouts()
	// examples.NonBlockChannelOperations()
	// examples.ClosingChannels()
	// examples.RangeOverChannels()
	// examples.Timers()
	// examples.Tickers()
	// examples.WorkerPools()
	// examples.WaitGroups()
	// examples.RateLimiting()
	// examples.AtomicCounters()
	// examples.Mutexes()
	// examples.Sorting()
	// examples.SortingByFunctions()
	// examples.Panic()
	// examples.Defer()
	// examples.CollectionFunctions()
	// examples.StringFunctions()
	// examples.StringFormatting()
	// examples.RegularExpressions()
	// examples.Json()
	// examples.Xml()
	// examples.Time()
	// examples.Epoch()
	// examples.TimeFormatingParsing()
	// examples.RandomNumbers()
	// examples.NumberParsing()
	// examples.UrlParsing()
	// examples.Sha1Hashes()
	// examples.Base64()
	// examples.ReadingFiles()
	// examples.WritingFiles()
	// examples.LineFilters()
	// examples.FilePaths()
	// examples.Directories()
	// examples.TemporaryDirectories()
	// examples.Testing()
	// examples.CommandLineArguments()
	// examples.CommandLineFlags()
	// examples.CommandLineSubcommands()
	// examples.EnvironmentVariables()
	examples.HttpClients()
}
